### ISSUE TITLE
zeppelin 0.9preview1: IRKernel not working

### ISSUE THREAD

**Issue by garyfeng** [garyfeng/flink-sql-demo#7]
Zeppelin supports two R kernels:
- `%r.r` (Vanilla r interpreter, with least dependencies, only R environment installed is required)
- `%r.ir` (Provide more fancy R runtime via IRKernel, almost the same experience like using R in Jupyter.)

The `%r.r` kernel works fine. Got the following error trying to use the IR Kernel `%r.ir`

```
org.apache.zeppelin.interpreter.InterpreterException: org.apache.zeppelin.interpreter.InterpreterException: Fail to init IR Kernel:
java.io.IOException: Fail to setup JVMGateway

	at org.apache.zeppelin.r.IRInterpreter.initIRKernel(IRInterpreter.java:140)
	at org.apache.zeppelin.r.IRInterpreter.open(IRInterpreter.java:106)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:668)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:577)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:130)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:668)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:577)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:130)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zeppelin.interpreter.InterpreterException: Fail to init IR Kernel:
java.io.IOException: Fail to setup JVMGateway

	at org.apache.zeppelin.r.IRInterpreter.initIRKernel(IRInterpreter.java:140)
	at org.apache.zeppelin.r.IRInterpreter.open(IRInterpreter.java:106)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:668)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:577)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:130)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.zeppelin.r.IRInterpreter.open(IRInterpreter.java:109)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	... 8 more
Caused by: java.io.IOException: Fail to setup JVMGateway

	at org.apache.zeppelin.r.IRInterpreter.initIRKernel(IRInterpreter.java:140)
	at org.apache.zeppelin.r.IRInterpreter.open(IRInterpreter.java:106)
	... 9 more
```

**Comment by garyfeng** [comment]
Error remains after installing dependencies in the Dockerfile for zeppelin

```dockerfile
# install Jupyter etc.
RUN pip install -q jupyter grpcio protobuf
```
